### PR TITLE
SPM version support

### PR DESCRIPTION
**Pull request by gpe08**
### Description

This PR adds a different way to expose the version when exporting the framework through SPM. Unfortunately, the Info.plist cannot be added to packages, so the current way to expose the version (`CFBundleShortVersionString`) is not friendly to the SPM Users. 

Under the Core Video Team in Sky, we are using mamba through SPM, and this is stopping us from using the framework in debug at all (and causing bigger issues in our Unit tests).

This PR just appends a hotfix to the problem, but I am open to updating it with a proper versioning solution were the maintaining team to propose one. Of course having the value hardcoded into Mamba.swift is far from ideal, but I would not want to impose any options either.

### Change Notes

* Returned a different version when the SWIFT_PACKAGE flag is set to true.

### Pre-submission Checklist

- [x] I ran the unit tests locally before checking in.
- [x] I made sure there were no compiler warnings before checking in.
- [ ] I have written useful documentation for all public code.
- [ ] I have written unit tests for this new feature.

### CODE REVIEW

**Review by jonnybach — APPROVED** [review]
Change looks good.  We can look into solution to move the version string literal out of the source file in future PRs.

**Review by jonnybach — CHANGES_REQUESTED** [review]
@gpe08, I've done a little more thinking on this and would like to propose a minor modification as follows:

1.  Create a `VERSION` or `version` plain text file and define the version text string there
2. Add this file as a Swift package resource according to [these instructions](https://developer.apple.com/documentation/swift_packages/bundling_resources_with_a_swift_package)
3. Assign version in `#if SWIFT_PACKAGE` by accessing the bundle resource.

Would this work?  I think doing this would make finding/modifying the package version a little easier and still accomplish the goal of being able to have a runtime accessible property.

**Comment by gpe08** [comment]
@jonnybach that should work fine indeed. I will look into it asap. (Sorry, I was on leave yesterday)

**Comment by gpe08** [comment]
@jonnybach Just pushed some commits to fix this problem. The bundling is a bit trickier with SPM than with other processes, so I had to append some suffixes to the path on the bundle. 

This has to do with bundle nesting and it's supposed to work with Bundle.module, however, that does not seem to work well in Xcode 12.

**Comment by jonnybach** [comment]
@gpe08 , sorry i was out on leave yesterday and just had a chance to look at this PR.  Thanks for making the code changes.  I want to understand more about the problem you faced when attempting to use the `Bundle.module.path(forResource: "version", ofType: "txt")` approach as opposed to what you have in this PR.

I attempted to recreate the problem by creating a dummy `MySwiftPackage` project in Xcode 12.5.1 with the following setup:
```swift
// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "MySwiftPackage",
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "MySwiftPackage",
            targets: ["MySwiftPackage"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(name: "mamba", path: "/Users/jbachm182/Projects/mamba_pr"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "MySwiftPackage",
            dependencies: ["mamba"]),
        .testTarget(
            name: "MySwiftPackageTests",
            dependencies: ["MySwiftPackage"]),
    ]
)
```

I then referenced the `mamba.FrameworkInfo.version` property in my dummy test app but modified your code in the PR to:
```swift
    private static var versionFilePathUrl: String? {
        let verPath = Bundle.module.path(forResource: "version", ofType: "txt")
        return verPath
    }
```

And had no issues fetching the version file.  Perhaps my test package is too trivial and I need to modify how it's configured?

**Comment by gpe08** [comment]
@jonnybach  Sorry, I've had too many things on my plate lately. When working on xcode 12.5.1, the oacjage itself would neither index the module method nor compile when I added it, so I could not get it to work. This is inside the module, not from the project using it. 

I was able to get it working on the debugger, by doing `po Bundle.module` but in the code itself, the project would not compile for me at all. I had the same when using internal packages in our repository. I am a bit lost to the reasoning behind it.

**Comment by jonnybach** [comment]
No apologies necessary @gpe08!  Do you have a sample project to share that demonstrates this?  I'd like to look into this a bit more to get a good understanding.

**Comment by gpe08** [comment]
@jonnybach Seems like those issues I had were Xcode being Xcode for me, and I can now get this working. I played around with the version.txt and things seem to work fine in our tests. Seems like it was caching an older mamba version somehow. 

So, I'm happy to go with the Bundle.module version, and sorry about all the noise.

**Review by jonnybach — APPROVED** [review]
No worries @gpe08, glad you were able to figure out it was just an Xcode issue of sorts.  Changes look good, thanks for implementing this and putting up with all my questions!

**Pull request merged**
