### PR TITLE
Added Xcode 16 adaptation for version 2.2.2.

### PR DESCRIPTION
**Pull request by kimbely0320**
### Description

Added Xcode 16 adaptation for version 2.2.2.

### Change Notes

* Added #include <stdint.h> for  RapidParserNewTagCallbacks.h & RapidParserState.h & RapidParserStateHandlers.h

### Pre-submission Checklist

- [x] I ran the unit tests locally before checking in.
- [x] I made sure there were no compiler warnings before checking in.
- [x] I have written useful documentation for all public code.
- [ ] I have written unit tests for this new feature.

### CODE REVIEW

**Comment by theRealRobG** [comment]
Hey, sorry I just noticed the issue you opened 2 weeks ago.

The changes you're looking to apply have already been merged in this PR: https://github.com/Comcast/mamba/pull/126

It seems that the branch you are working from is just several commits behind (35 actually). I believe that if I merge the latest changes from `develop` into your branch the only remaining change will be the version bump in the podspec file. Are you OK for me to try merging back up and seeing the result?

Also, there are a few more locations to bump the version, particularly the MARKETING_VERSION values within the xcodeproj. I know the version bumping within the files has been fairly lackluster, but I'm looking to improve this, and hopefully the release process too.

Perhaps this command (at the root of the repo) can make the version bump easier:
For macOS:
```sh
sed -i '' "s/MARKETING_VERSION = [0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\};/MARKETING_VERSION = 2.2.3;/" ./mamba.xcodeproj/project.pbxproj
```
For Linux:
```sh
sed -i "s/MARKETING_VERSION = [0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\};/MARKETING_VERSION = 2.2.3;/" ./mamba.xcodeproj/project.pbxproj
```
Difference explained: https://stackoverflow.com/a/4247319

Are you ultimately looking for an official release tag update _(to 2.2.3)_ with the compilation fixes?

**Comment by kimbely0320** [comment]
Hi, thanks for the update! I’m totally fine with you proceeding as suggested. Please go ahead and merge the latest changes from develop into my branch, and let’s see how it looks after. I’m also okay with the version bump and any necessary updates to the MARKETING_VERSION values within the project.

Thanks for improving the process, and yes, it would be great to have an official release tag update to 2.2.3 with the compilation fixes!

**Comment by theRealRobG** [comment]
No problem.

I just merged and the changelog is now showing that the change is just the version bump to the podspec.

Could you bump all of the MARKETING_VERSION values in `./mamba.xcodeproj/project.pbxproj`?

After that I can merge and I should be able to create a release tag from there _(will likely have to wait until tomorrow, US Eastern, just to double-check with the other maintainer on the correct process)_.

Thanks for the contribution and patience!

**Comment by kimbely0320** [comment]
Hi, I have completed the update and bumped all the MARKETING_VERSION values in ./mamba.xcodeproj/project.pbxproj.

Let me know if there’s anything else needed before the release.

Thanks for the guidance!

**Review by theRealRobG — APPROVED** [review]

**Comment by theRealRobG** [comment]
Hey @kimbely0320 , I think we're actually going to release this change as part of the `2.3.0` version here: #140 

There have been a few other additions since 2.2.2 so I believe a minor bump is more accurate than a patch.

**Comment by kimbely0320** [comment]
Ok, thank you again for your assistance.Robert Galluccio ***@***.***> 於 2024年10月4日 凌晨3:23 寫道：﻿
Hey @kimbely0320 , I think we're actually going to release this change as part of the 2.3.0 version here: #140
There have been a few other additions since 2.2.2 so I believe a minor bump is more accurate than a patch.

**Comment by theRealRobG** [comment]
@kimbely0320 the changes are now available in release [2.3.0](https://github.com/Comcast/mamba/releases/tag/2.3.0).

Thanks for the patience.

**Pull request merged**
